### ISSUE TITLE
Partition skew when TensorizeIn computes 'max' of its integer columns

### ISSUE THREAD

**Issue by ddicato** [linkedin/Avro2TF#20]
There appears to be an intermittent performance issue, where the "head at TensorMetadataGeneration.scala:113" job can take almost an hour in a single executor, while all other executors take less than 1-2 minutes.

Perhaps `agg(Map[String, String])` is less efficient (or less Catalyst-optimizable) than `agg(Column, Column*)`.

**Comment by cyzhangchenya** [comment]
Hi @ddicato, thanks for raising this up.

Some follow-up items:
- Could we confirm if it is an intermittent performance issue? It might be caused by cluster instability.
- I'm okay to check in this change. But we might need your help to experiment and monitor its performance with some more experiments.

Please let me know what you think.
